---
title: Symptom analysis
output:
  html_document:
  toc: true
  toc_float: true
---

```{r setup}
#set working directory
knitr::opts_knit$set(root.dir = 'S:/LLC_0028/data/symptom_analysis')
```

# Logistic Regression

## R setup

```{r setup 2}
#import packages
library(ggplot2)
library(lme4)
library(sjPlot)
library(dplyr)

#read data

#data includes participants with symptoms. This is used for clustering analysis
data<-read.csv("S:/LLC_0028/data/harmonised_all/llc_0028_full_harmonised_data.csv")
data<-data.frame(data)

#keep required variables
vars_<-c('fever','cough','throat','chest_tight','breath',
         'nose','aches','fatigue','diarrhoea','smell_taste','nausea_vomit',
         'rash','sneezing','headache','appetite','tummy_ache','eyes','voice',
         'dizzy','chest_pain','chills','sleep','numb','heavy','swelling',
         'concentrating','memory','covid_status', 'study')

data<-data[vars_]

#one participant has covid_status nan. Replace with 0.
data[is.na(data)]<- 0 
```

## Create symptom vectors and models

```{r create models}

#symptom lists
core_symptoms <- as.list(c('fever','cough','throat','chest_tight','breath',
         'nose','aches','fatigue','diarrhoea','smell_taste','nausea_vomit',
         'rash','sneezing','headache','concentrating','memory'))

max_symptoms <- as.list(c('fever','cough','throat','chest_tight','breath',
         'nose','aches','fatigue','diarrhoea','smell_taste','nausea_vomit',
         'rash','sneezing','headache','appetite','tummy_ache','eyes','voice',
         'dizzy','chest_pain','chills','sleep','numb','heavy','swelling',
         'concentrating','memory'))

#model lists

core_model_list <- lapply(paste('covid_status ~',core_symptoms,'+ (1|study)'),
                          as.formula)

max_model_list <- lapply(paste('covid_status ~',max_symptoms,'+ (1|study)'),
                         as.formula)
```

## Core symptoms

### No covid, vs covid <12 weeks ago

```{r 0 vs 1 core}

#extract participants with covid ststus 0 or 1
df <- subset(data, covid_status %in% c(0,1))

#fit logistic regression with random effect for study

results_list <- lapply(core_model_list,
                       function(x) glmer(x,
                                         data=df,
                                         family=binomial(link='logit')))

```

#### Combine and save results

```{r save 1}

results <- data.frame()

for (i in seq_along(results_list)){
  
  model_results <- as.data.frame(coef(summary(results_list[[i]])))
  
  #add confidence itervals
  conf_int <- confint.merMod(results_list[[i]], method = 'Wald')
  conf_int <- as.data.frame(conf_int[-1,])
  
  #merge with model_results
  model_results <- cbind(model_results, conf_int)
  
  # dont include intercept at index 1
  results <- bind_rows(results, model_results[-1,])

}

#exponate columns for odds-ratios
to_raise <- c('Estimate','Std. Error', '2.5 %', '97.5 %')

results[to_raise] <- exp(results[to_raise])

#save

fname = 'lr_results_0_1_core'

write.csv(results,
          paste("S:/LLC_0028/data/symptom_analysis/", fname, "_.csv", sep=""),
          row.names = TRUE)
```


### No covid, vs covid >12 weeks ago

```{r 0 vs 2 core}
df <- subset(data, covid_status %in% c(0,2))

# replace covid status 2 with 1
df$covid_status[df$covid_status==2]<- 1

results_list <- lapply(core_model_list,
                       function(x) glmer(x,
                                         data=df,
                                         family=binomial(link='logit')))

```


#### Combine and save results

```{r save 2}

results <- data.frame()

for (i in seq_along(results_list)){
  
  model_results <- as.data.frame(coef(summary(results_list[[i]])))
  
  #add confidence itervals
  conf_int <- confint.merMod(results_list[[i]], method = 'Wald')
  conf_int <- as.data.frame(conf_int[-1,])
  
  #merge with model_results
  model_results <- cbind(model_results, conf_int)
  
  results <- bind_rows(results, model_results[-1,])

}

#exponate columns for odds-ratios
to_raise <- c('Estimate','Std. Error', '2.5 %', '97.5 %')

results[to_raise] <- exp(results[to_raise])

#save
fname = 'lr_results_0_2_core'

write.csv(results,
          paste("S:/LLC_0028/data/symptom_analysis/", fname, "_.csv", sep=""),
          row.names = TRUE)
```


## All symptoms

### No covid, vs covid <12 weeks ago

```{r 0 vs 1 max}
df <- subset(data, covid_status %in% c(0,1))

#only studies with maximal symptoms
maximal<- c('alspac','bib','twins','track19')

df <- subset(df, study %in% maximal)

#fit logistic regression with random effect for study

results_list <- lapply(max_model_list, 
                       function(x) glmer(x, 
                                         data=df, 
                                         family=binomial(link='logit'),
                                         control = glmerControl(
                                           optimizer='bobyqa',
                                           optCtrl = list(maxfun=10000))))

```


#### Combine and save results

```{r save 3}

results <- data.frame()

for (i in seq_along(results_list)){
  
  model_results <- as.data.frame(coef(summary(results_list[[i]])))
  
  #add confidence itervals
  conf_int <- confint.merMod(results_list[[i]], method = 'Wald')
  conf_int <- as.data.frame(conf_int[-1,])
  
  #merge with model_results
  model_results <- cbind(model_results, conf_int)
  
  results <- bind_rows(results, model_results[-1,])

}

#exponate columns for odds-ratios
to_raise <- c('Estimate','Std. Error', '2.5 %', '97.5 %')

results[to_raise] <- exp(results[to_raise])

#save
fname = 'lr_results_0_1_max'

write.csv(results,
          paste("S:/LLC_0028/data/symptom_analysis/", fname, "_.csv", sep=""),
          row.names = TRUE)
```


### No covid, vs covid >12 weeks ago

```{r 0 vs 2 max}
df <- subset(data, covid_status %in% c(0,2))
# replace covid status 2 with 1
df$covid_status[df$covid_status==2]<- 1

#only studies with maximal symptoms
maximal<- c('alspac','bib','twins','track19')

results_list <- lapply(max_model_list, 
                       function(x) glmer(x, 
                                         data=df, 
                                         family=binomial(link='logit'),
                                         control = glmerControl(
                                           optimizer='bobyqa',
                                           optCtrl = list(maxfun=10000))))

```


#### Combine and save results

```{r save 4}

results <- data.frame()

for (i in seq_along(results_list)){
  
  model_results <- as.data.frame(coef(summary(results_list[[i]])))
  
  #add confidence itervals
  conf_int <- confint.merMod(results_list[[i]], method = 'Wald')
  conf_int <- as.data.frame(conf_int[-1,])
  
  #merge with model_results
  model_results <- cbind(model_results, conf_int)
  
  results <- bind_rows(results, model_results[-1,])

}

#exponate columns for odds-ratios
to_raise <- c('Estimate','Std. Error', '2.5 %', '97.5 %')

results[to_raise] <- exp(results[to_raise])

#save
fname = 'lr_results_0_2_max'

write.csv(results,
          paste("S:/LLC_0028/data/symptom_analysis/", fname, "_.csv", sep=""),
          row.names = TRUE)
```

